# Generated by Django 5.1.6 on 2025-02-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view books'), ('can_create', 'Can add books'), ('can_edit', 'Can change books'), ('can_delete', 'Can delete books')]},
        ),
    ]
